> lengths(Datos)
> lengths(Localidades)
Dif_AJ <- setdiff("Datos","Localidades")
> Dif_AJ <- setdiff("Jal-loc","Jal-mun")
> Dif_AJ <- setdiff("Datos","Localidades")
> Dif_AJ <- setdiff("Jal_loc","Jal_mun")
> Dif_AJ <- setdiff("Zac_loc","Zac_mun")
> Co_AJ <- intersect("Datos","Localidades")
> Co_AJ <- intersect("Jal-loc","Jal-mun")
> Co_AJ <- intersect("Datos","Localidades")
> Co_AJ <- intersect("Jal_loc","Jal_mun")
> Co_AJ <- intersect("Zac_loc","Zac_mun")